### PR TITLE
fix: Toggle rotate look down-side when opened

### PR DESCRIPTION
**Pull request by JoSuwon**
# Description of Changes

* Toggle rotate look down-side when opened
* The shape of the toggle triangle was slightly modified.
* Add pointer cursor

## Video
* as is

https://github.com/user-attachments/assets/fc7d2d97-ab53-47ab-b4ec-3512a48acdd0

* to be

https://github.com/user-attachments/assets/d79b418a-ee56-47f6-b0d0-bee319873e64

### CODE REVIEW

**Comment by JoSuwon** [comment]
This is my first time using Storybook, so I found it difficult. How do I test the components in dark mode? A problem is expected as the toggle will not be visible properly when the background is in dark mode.

**Comment by JoSuwon** [comment]
한글로 올려도 되는거죠 .. ? 영문으로만 가능한가요 ?

**Comment by Moon-DaeSeung** [comment]
it's global library~ english only on pr

**Comment by Moon-DaeSeung** [comment]
umm could you upload original(?) bug too?

you uploaded fixed version right?

**Comment by Moon-DaeSeung** [comment]
> This is my first time using Storybook, so I found it difficult. How do I test the components in dark mode? A problem is expected as the toggle will not be visible properly when the background is in dark mode.

@JoSuwon https://discord.gg/yAjKwDb7xR 

join discord!

**Comment by JoSuwon** [comment]
https://github.com/user-attachments/assets/fc7d2d97-ab53-47ab-b4ec-3512a48acdd0

this is upstream main branch's toggle-component

**Comment by JoSuwon** [comment]
> umm could you upload original(?) bug too? 

upload completed (in first comment)

> you uploaded fixed version right?

yes

@Moon-DaeSeung

**Review by Moon-DaeSeung — APPROVED** [review]
LGTM!!

**Pull request merged**
